#!/usr/bin/env python3
"""Verify Janus's exact Aeon stage-handoff and journey contract pins (JANUS-480).

Offline, this checks the vendored OpenAPI excerpt and manifest bytes and that
the Rust reporter constants name the same Aeon release, commit, and OpenAPI
digest. With --aeon-checkout it also re-derives the excerpt from that commit's
api/openapi.yaml and requires identical bytes. With --write-excerpt it
regenerates the excerpt from a checkout for a reviewed pin update.

The classic Paimos external-stage v1 pins are checked separately by
check-paimos-external-stage-pins.py and stay unchanged for old attempts.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

CONTRACT_DIRECTORY = Path("contracts/aeon-stage-handoff-v1")
EXCERPT = "openapi-excerpt-v1.yaml"
MANIFEST = "manifest-v1.json"
RUST_SOURCE = Path("crates/janus-host/src/aeon_stage.rs")
EXPECTED_MANIFEST_SHA256 = "90089c59cd37e57261e2743b3a291f27067be95c6357894c21f6fe2a337e2764"
EXPECTED_EXCERPT = (13191, "ad2ff0ba394acda8667f311d03b33ff0c5d682ef9b6b1d6c4c488feb6fd517f8")
CONTRACT = "inspr.aeon.stage-handoff.v1"
RELEASE = "v260926071154.0.0"
COMMIT = "482c563482c014c2097e65f7ef528444e12ec7af"
SPEC_SHA256 = "4420f2d269af7477bcb41a7fa0d670f28376a151145c71ebb368c61ade370493"
PATHS = (
    "/projects/{projectId}/journey",
    "/stage-handoffs/{handoffId}",
    "/stage-handoffs/{handoffId}/evidence",
    "/stage-handoffs/{handoffId}/result",
)
SCHEMAS = (
    "Journey",
    "JourneyLaunchReadiness",
    "JourneyStage",
    "JourneyNextAction",
    "StageHandoff",
    "StageEvidenceWrite",
    "StageEvidence",
    "StageArtifact",
    "StageResultWrite",
    "StageResult",
)
RUST_CONSTANTS = {
    "AEON_STAGE_CONTRACT": CONTRACT,
    "AEON_STAGE_RELEASE": RELEASE,
    "AEON_STAGE_COMMIT": COMMIT,
    "AEON_OPENAPI_SHA256": SPEC_SHA256,
}


def digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def block(lines: list[str], header: str, indent: int) -> list[str]:
    """Return one YAML mapping entry at `indent` with its nested lines."""
    prefix = " " * indent
    starts = [
        index
        for index, line in enumerate(lines)
        if line == f"{prefix}{header}:" or line.startswith(f"{prefix}{header}: ")
    ]
    if len(starts) != 1:
        raise ValueError(f"openapi entry not found exactly once: {header}")
    start = starts[0]
    end = start + 1
    while end < len(lines):
        line = lines[end]
        if line.strip() and len(line) - len(line.lstrip(" ")) <= indent:
            break
        end += 1
    return lines[start:end]


def excerpt(openapi: bytes) -> bytes:
    lines = openapi.decode("utf-8").split("\n")
    output = [
        f"# Aeon {RELEASE} ({COMMIT}) api/openapi.yaml sha256 {SPEC_SHA256}",
        "# Generated by scripts/check-aeon-stage-handoff-pins.py --write-excerpt; do not edit.",
        "paths:",
    ]
    for path in PATHS:
        output.extend(block(lines, path, 2))
    output.append("components:")
    output.append("  securitySchemes:")
    output.extend(block(lines, "agentKey", 4))
    output.append("  schemas:")
    for schema in SCHEMAS:
        output.extend(block(lines, schema, 4))
    return ("\n".join(line.rstrip() for line in output) + "\n").encode("utf-8")


def openapi_at(checkout: Path) -> bytes:
    raw = subprocess.run(
        ["git", "-C", str(checkout), "show", f"{COMMIT}:api/openapi.yaml"],
        check=True,
        capture_output=True,
    ).stdout
    if digest(raw) != SPEC_SHA256:
        raise ValueError("Aeon openapi.yaml at the pinned commit drifted")
    return raw


def verify_rust(repo_root: Path) -> None:
    source = (repo_root / RUST_SOURCE).read_text(encoding="utf-8")
    for name, expected in RUST_CONSTANTS.items():
        match = re.search(rf'pub const {name}: &str =\s*"([^"]*)";', source)
        if match is None or match.group(1) != expected:
            raise ValueError(f"Rust reporter pin drifted: {name}")


def verify(repo_root: Path, checkout: Path | None) -> None:
    contract = repo_root / CONTRACT_DIRECTORY
    inventory = {path.name for path in contract.iterdir() if path.is_file()}
    if inventory != {EXCERPT, MANIFEST}:
        raise ValueError("Aeon stage-handoff contract inventory drifted")

    manifest_raw = (contract / MANIFEST).read_bytes()
    if digest(manifest_raw) != EXPECTED_MANIFEST_SHA256:
        raise ValueError("Aeon stage-handoff manifest bytes drifted")
    manifest = json.loads(manifest_raw)
    expected_manifest = {
        "contract": CONTRACT,
        "aeon_release": RELEASE,
        "aeon_commit": COMMIT,
        "openapi_path": "api/openapi.yaml",
        "openapi_sha256": SPEC_SHA256,
        "paths": list(PATHS),
        "schemas": list(SCHEMAS),
        "excerpt": {
            "file": EXCERPT,
            "bytes": EXPECTED_EXCERPT[0],
            "sha256": EXPECTED_EXCERPT[1],
        },
    }
    if manifest != expected_manifest:
        raise ValueError("Aeon stage-handoff manifest tuple drifted")

    raw = (contract / EXCERPT).read_bytes()
    if len(raw) != EXPECTED_EXCERPT[0] or digest(raw) != EXPECTED_EXCERPT[1]:
        raise ValueError("Aeon stage-handoff OpenAPI excerpt drifted")
    if checkout is not None and excerpt(openapi_at(checkout)) != raw:
        raise ValueError("Aeon stage-handoff excerpt differs from the pinned commit")
    verify_rust(repo_root)


def self_test(repo_root: Path) -> None:
    verify(repo_root, None)
    for mutate in ("excerpt", "rust"):
        with tempfile.TemporaryDirectory() as temporary:
            test_root = Path(temporary)
            shutil.copytree(repo_root / CONTRACT_DIRECTORY, test_root / CONTRACT_DIRECTORY)
            (test_root / RUST_SOURCE).parent.mkdir(parents=True)
            shutil.copy(repo_root / RUST_SOURCE, test_root / RUST_SOURCE)
            if mutate == "excerpt":
                target = test_root / CONTRACT_DIRECTORY / EXCERPT
                target.write_bytes(target.read_bytes().replace(b"minimum: 1", b"minimum: 0", 1))
            else:
                target = test_root / RUST_SOURCE
                target.write_text(target.read_text().replace(COMMIT, "0" * 40, 1))
            try:
                verify(test_root, None)
            except ValueError:
                continue
            raise AssertionError(f"tampered Aeon pin was accepted: {mutate}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--aeon-checkout", type=Path)
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--write-excerpt", action="store_true")
    args = parser.parse_args()
    try:
        if args.write_excerpt:
            if args.aeon_checkout is None:
                raise ValueError("--write-excerpt needs --aeon-checkout")
            raw = excerpt(openapi_at(args.aeon_checkout))
            (args.repo_root / CONTRACT_DIRECTORY).mkdir(parents=True, exist_ok=True)
            (args.repo_root / CONTRACT_DIRECTORY / EXCERPT).write_bytes(raw)
            print(f"excerpt bytes={len(raw)} sha256={digest(raw)}")
        elif args.self_test:
            self_test(args.repo_root)
            print("Aeon stage-handoff pin verifier self-test passed")
        else:
            verify(args.repo_root, args.aeon_checkout)
            print("Aeon stage-handoff pins verified")
        return 0
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError,
            subprocess.CalledProcessError) as error:
        print(f"Aeon stage-handoff pins blocked: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
